extends:
  - "spectral:oas"

rules:
  info-description:
    description: Info "description" must be present and non-empty string.
    severity: warn
    given: $.info
    then:
      field: description
      function: truthy

  operation-description:
    description: Operation "description" must be present and non-empty string.
    severity: warn
    given: $.paths[*][*]
    then:
      field: description
      function: truthy
