extends: ["spectral:oas", "spectral:asyncapi"]
formats: ["oas3", "oas2"]

rules:
  info-contact: warn
  info-description: warn
  operation-description: warn
  operation-operationId: warn
  operation-tags: warn
  oas3-api-servers: warn