name: Проверка документации

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-markdown:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout кода
        uses: actions/checkout@v3

      - name: Установка MarkdownLint
        run: npm install -g markdownlint-cli

      - name: Проверка Markdown
        run: markdownlint "**/*.md" --config .markdownlint.json || exit 1

  validate-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout кода
        uses: actions/checkout@v3

      - name: Установка Lychee (проверка ссылок)
        uses: cathalgarvey/setup-lychee@v1

      - name: Проверка битых ссылок
        run: lychee "*.md" "docs/**/*.md"